### ISSUE TITLE
Suggestion: Show changelog via composer.lock log

### ISSUE THREAD

**Issue by rodnaph** [pyrech/composer-changelogs#24]
Hi, just a suggestion, no idea if it's possible, but it might be nice to be able to see this information dynamically for composer.lock instead of committing it to Git.  Something like...

```
$> composer changelog
```

Which would then `git log` composer.lock and do whatever stuff you're doing here to show the diff for each change.

But like I said, I haven't looked into how you need to compute this stuff so close this if it's a rubbish idea.

**Comment by pyrech** [comment]
Hi, thanks for your interest :)

I'm not sure I understand correctly your issue so I'm probably wrong. So you want to be able to generate a changelog between the current vendors and the ones from an older commit by comparing the two composer.lock.

But I'm afraid it would be hard to do it properly because currently, it's composer itself which does the stuff of computing install / update or removal of dependencies. So we would need to duplicate this logic, which is not worth it IMO.

**Comment by rodnaph** [comment]
It sounds like as you say you'd need to duplicate what Composer is doing, so not worth it.

What I meant though was that having some ability to look at a commit which changes composer.lock - and then working out from that the information you present as the extra Composer output.  So you wouldn't need to store it at all.

Never mind, looks like a useful tool!
